### ISSUE TITLE
Wrong Folder in README (at least for me)

### ISSUE THREAD

**Issue by koesherbacon** [savagezen/dnd-tools#13]
Your README.md says that the package will be executable from `/usr/bin/dnd-tools` but after my install it is in `/usr/local/bin/dnd-tools`.  Maybe it has something to do with my MX-Linux distro since it does not use systemd?

I'm going to be using this handy little package soon, thanks a lot :)

**Comment by savagezen** [comment]
If ```/usr/local/bin``` is in your ```$PATH``` then you can still execute via ```$ dnd-tools```.  If you do not see ```/usr/local/bin``` in the output of ```$ echo $PATH```, then:
```
$ nano ~/.bashrc
------
# add this line
export PATH=/usr/local/bin/:$PATH
-----
$ source  ~/.bashrc
$ dnd-tools
```

I'm not familiar with MX-Linux, though it shouldn't have to do with systemd.  What version of Python are you using?  Did you use ```sudo``` when running the install command?
